name: venv
channels:
- !!python/unicode
  'omnia'
- !!python/unicode
  'dlr-sc'
- !!python/unicode
  'jlmenut'
- !!python/unicode
  'bioconda'
- !!python/unicode
  'defaults'
dependencies:
- !!python/unicode
  'wkhtmltopdf=0.12.3=0'
- !!python/unicode
  'anaconda-client=1.6.3=py27_0'
- !!python/unicode
  'cffi=1.10.0=py27_0'
- !!python/unicode
  'clyent=1.2.2=py27_0'
- !!python/unicode
  'dbus=1.10.10=0'
- !!python/unicode
  'expat=2.1.0=0'
- !!python/unicode
  'fontconfig=2.12.1=3'
- !!python/unicode
  'freetype=2.5.5=2'
- !!python/unicode
  'glib=2.50.2=1'
- !!python/unicode
  'gst-plugins-base=1.8.0=0'
- !!python/unicode
  'gstreamer=1.8.0=0'
- !!python/unicode
  'icu=54.1=0'
- !!python/unicode
  'jpeg=9b=0'
- !!python/unicode
  'libffi=3.2.1=1'
- !!python/unicode
  'libgcc=5.2.0=0'
- !!python/unicode
  'libiconv=1.14=0'
- !!python/unicode
  'libpng=1.6.27=0'
- !!python/unicode
  'libxcb=1.12=1'
- !!python/unicode
  'mkl=2017.0.1=0'
- !!python/unicode
  'numpy=1.12.1=py27_0'
- !!python/unicode
  'openssl=1.0.2k=2'
- !!python/unicode
  'pcre=8.39=1'
- !!python/unicode
  'pip=9.0.1=py27_1'
- !!python/unicode
  'pycparser=2.17=py27_0'
- !!python/unicode
  'pyparsing=2.1.4=py27_0'
- !!python/unicode
  'pyqt=4.10.4=py27_0'
- !!python/unicode
  'python=2.7.13=0'
- !!python/unicode
  'python-dateutil=2.6.0=py27_0'
- !!python/unicode
  'pytz=2017.2=py27_0'
- !!python/unicode
  'pyyaml=3.12=py27_0'
- !!python/unicode
  'qt=4.8.5=0'
- !!python/unicode
  'readline=6.2=2'
- !!python/unicode
  'requests=2.14.2=py27_0'
- !!python/unicode
  'setuptools=27.2.0=py27_0'
- !!python/unicode
  'sip=4.15.5=py27_0'
- !!python/unicode
  'six=1.10.0=py27_0'
- !!python/unicode
  'sqlite=3.13.0=0'
- !!python/unicode
  'tk=8.5.18=0'
- !!python/unicode
  'wheel=0.29.0=py27_0'
- !!python/unicode
  'yaml=0.1.6=0'
- !!python/unicode
  'zlib=1.2.8=3'
- !!python/unicode
  'freeimageplus=3.17.0=0'
- !!python/unicode
  'gl2ps=1.3.8=1'
- !!python/unicode
  'libxml2=2.9.3=1'
- !!python/unicode
  'oce=0.17.2=3'
- !!python/unicode
  'pythonocc-core=0.17=py27_0'
- !!python/unicode
  'tbb=4.3.6=0'
- !!python/unicode
  'cairocffi=0.6=py27_0'
- !!python/unicode
  'cairosvg=1.0.13=py27_0'
- !!python/unicode
  'svgwrite=1.1.6=py27_0'
- pip:
  - pdfkit==0.6.1
